set autoindent
set cindent
set smartindent
set wrap
set nowrapscan
set nobackup
set visualbell
set ruler
set shiftwidth=4
set number
set fencs=ucs-bom,utf-8,euc-kr.latin1
set fileencoding=utf-8
set tenc=utf-8
set expandtab
set hlsearch
set ignorecase
set tabstop=4
set lbr
set incsearch
set background=dark
set backspace=eol,start,indent
set history=1000
set nocompatible
set backspace=2
